-- conferences: SleepingPill conferenceId used as PK directly
CREATE TABLE conferences (
    id   VARCHAR(100) PRIMARY KEY,
    slug VARCHAR(200) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    year INT  NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false
);

-- speakers: ID derived from lowercased name, stable across re-imports
CREATE TABLE speakers (
    id         VARCHAR(100) PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX speakers_name_gin ON speakers USING GIN (to_tsvector('simple', name));

-- videos: SleepingPill session id as PK
CREATE TABLE videos (
    id                VARCHAR(100) PRIMARY KEY,
    conference_id     VARCHAR(100) NOT NULL REFERENCES conferences (id),
    title             TEXT NOT NULL,
    abstract          TEXT,
    intended_audience TEXT,
    vimeo_id          VARCHAR(60) NOT NULL,
    language          VARCHAR(10),
    format            VARCHAR(200),
    length_minutes    INT,
    room              VARCHAR(200),
    start_time        TIMESTAMPTZ,
    end_time          TIMESTAMPTZ,
    keywords          VARCHAR(200)[], -- from suggestedKeywords CSV (SleepingPill, unchanged)
    ai_keywords       VARCHAR(200)[], -- additional keywords generated by AI
    title_en          TEXT,   -- English version (AI-generated or original)
    abstract_en       TEXT,
    intended_audience_en TEXT,
    title_no          TEXT,   -- Norwegian version (AI-generated or original)
    abstract_no       TEXT,
    intended_audience_no TEXT,
    search_vector_en  TSVECTOR,
    search_vector_no  TSVECTOR,
    base_score        INT         NOT NULL DEFAULT 0, -- recency rank, recalculated on each import
    view_boost        INT         NOT NULL DEFAULT 0, -- updated from video_events at end of import
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX videos_score_idx    ON videos ((base_score + view_boost) DESC);
CREATE INDEX videos_search_en_idx ON videos USING GIN (search_vector_en);
CREATE INDEX videos_search_no_idx ON videos USING GIN (search_vector_no);
CREATE INDEX videos_conf_idx     ON videos (conference_id);

-- video_speakers: join table, bio is per (video, speaker) pair as it changes yearly
CREATE TABLE video_speakers (
    video_id          VARCHAR(100) NOT NULL REFERENCES videos (id) ON DELETE CASCADE,
    speaker_id        VARCHAR(100) NOT NULL REFERENCES speakers (id),
    bio               TEXT,
    bio_search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', coalesce(bio, ''))) STORED,
    PRIMARY KEY (video_id, speaker_id)
);
CREATE INDEX video_speakers_bio_idx ON video_speakers USING GIN (bio_search_vector);

-- video_events: every play/pause/progress/ended/seek event from the frontend
CREATE TYPE video_event_type AS ENUM ('play', 'pause', 'progress', 'ended', 'seek');
CREATE TABLE video_events (
    id                     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id               VARCHAR(100)     NOT NULL REFERENCES videos (id),
    user_uuid              VARCHAR(100)     NOT NULL,
    event_type             video_event_type NOT NULL,
    playback_position_secs INT,
    created_at             TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX video_events_video_id_idx  ON video_events (video_id);
CREATE INDEX video_events_created_at_idx ON video_events (created_at);

-- search_logs: every search query for analytics
CREATE TABLE search_logs (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    query         VARCHAR(500) NOT NULL,
    results_count INT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- video_view_stats: aggregates video_events data — no separate table needed.
-- unique_viewers    = distinct user_uuids who sent a 'play' event (all time)
-- viewers_last_7d   = same, but only from the last 7 days
-- Used by: GET /api/videos/trending  and  view_boost recalculation in VideoImporter
CREATE VIEW video_view_stats AS
SELECT video_id,
       COUNT(DISTINCT user_uuid)                                                        AS unique_viewers,
       COUNT(DISTINCT CASE WHEN created_at >= now() - INTERVAL '7 days' THEN user_uuid END) AS viewers_last_7d
FROM video_events
WHERE event_type = 'play'
GROUP BY video_id;

-- video_impressions: backend tracking of surfaced videos
CREATE TABLE video_impressions (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    video_id      VARCHAR(100) NOT NULL REFERENCES videos(id),
    endpoint      VARCHAR(100), -- e.g. 'list', 'search', 'trending', 'related'
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
